package info

//go:generate go run github.com/abice/go-enum -f=$GOFILE --marshal --names

// StocksRequestFilterVisibility
// ENUM(ALL=0, VISIBLE, INVISIBLE, EMPTY_STOCK, NOT_MODERATED, MODERATED, DISABLED, STATE_FAILED, READY_TO_SUPPLY, VALIDATION_STATE_PENDING, VALIDATION_STATE_FAIL, VALIDATION_STATE_SUCCESS, TO_SUPPLY, IN_SALE, REMOVED_FROM_SALE, BANNED, OVERPRICED, CRITICALLY_OVERPRICED, EMPTY_BARCODE, BARCODE_EXISTS, QUARANTINE, ARCHIVED, OVERPRICED_WITH_STOCK, PARTIAL_APPROVED, IMAGE_ABSENT, MODERATION_BLOCK)
type StocksRequestFilterVisibility int32

// ListResponseItemErrorLevel
// ENUM(ERROR_LEVEL_UNSPECIFIED=0, ERROR_LEVEL_ERROR, ERROR_LEVEL_WARNING, ERROR_LEVEL_INTERNAL)
type ListResponseItemErrorLevel int32

// ListResponseItemPriceIndexesColorIndex
// ENUM(COLOR_INDEX_UNSPECIFIED=0, COLOR_INDEX_WITHOUT_INDEX, COLOR_INDEX_GREEN, COLOR_INDEX_YELLOW, COLOR_INDEX_RED)
type ListResponseItemPriceIndexesColorIndex int32

// ListResponseItemSourceShipmentType
// ENUM(SHIPMENT_TYPE_UNSPECIFIED=0, SHIPMENT_TYPE_GENERAL, SHIPMENT_TYPE_BOX, SHIPMENT_TYPE_PALLET)
type ListResponseItemSourceShipmentType int32
