// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package transaction

import (
	"fmt"
	"strings"
)

const (
	// ListResponseResultOperationPostingDeliverySchemaFBO is a ListResponseResultOperationPostingDeliverySchema of type FBO.
	ListResponseResultOperationPostingDeliverySchemaFBO ListResponseResultOperationPostingDeliverySchema = iota + 1
	// ListResponseResultOperationPostingDeliverySchemaFBS is a ListResponseResultOperationPostingDeliverySchema of type FBS.
	ListResponseResultOperationPostingDeliverySchemaFBS
	// ListResponseResultOperationPostingDeliverySchemaCROSSBORDER is a ListResponseResultOperationPostingDeliverySchema of type CROSSBORDER.
	ListResponseResultOperationPostingDeliverySchemaCROSSBORDER
	// ListResponseResultOperationPostingDeliverySchemaRFBS is a ListResponseResultOperationPostingDeliverySchema of type RFBS.
	ListResponseResultOperationPostingDeliverySchemaRFBS
	// ListResponseResultOperationPostingDeliverySchemaFBP is a ListResponseResultOperationPostingDeliverySchema of type FBP.
	ListResponseResultOperationPostingDeliverySchemaFBP
	// ListResponseResultOperationPostingDeliverySchemaFBOECONOMY is a ListResponseResultOperationPostingDeliverySchema of type FBOECONOMY.
	ListResponseResultOperationPostingDeliverySchemaFBOECONOMY
	// ListResponseResultOperationPostingDeliverySchemaFBSECONOMY is a ListResponseResultOperationPostingDeliverySchema of type FBSECONOMY.
	ListResponseResultOperationPostingDeliverySchemaFBSECONOMY
)

var ErrInvalidListResponseResultOperationPostingDeliverySchema = fmt.Errorf("not a valid ListResponseResultOperationPostingDeliverySchema, try [%s]", strings.Join(_ListResponseResultOperationPostingDeliverySchemaNames, ", "))

const _ListResponseResultOperationPostingDeliverySchemaName = "FBOFBSCROSSBORDERRFBSFBPFBOECONOMYFBSECONOMY"

var _ListResponseResultOperationPostingDeliverySchemaNames = []string{
	_ListResponseResultOperationPostingDeliverySchemaName[0:3],
	_ListResponseResultOperationPostingDeliverySchemaName[3:6],
	_ListResponseResultOperationPostingDeliverySchemaName[6:17],
	_ListResponseResultOperationPostingDeliverySchemaName[17:21],
	_ListResponseResultOperationPostingDeliverySchemaName[21:24],
	_ListResponseResultOperationPostingDeliverySchemaName[24:34],
	_ListResponseResultOperationPostingDeliverySchemaName[34:44],
}

// ListResponseResultOperationPostingDeliverySchemaNames returns a list of possible string values of ListResponseResultOperationPostingDeliverySchema.
func ListResponseResultOperationPostingDeliverySchemaNames() []string {
	tmp := make([]string, len(_ListResponseResultOperationPostingDeliverySchemaNames))
	copy(tmp, _ListResponseResultOperationPostingDeliverySchemaNames)
	return tmp
}

var _ListResponseResultOperationPostingDeliverySchemaMap = map[ListResponseResultOperationPostingDeliverySchema]string{
	ListResponseResultOperationPostingDeliverySchemaFBO:         _ListResponseResultOperationPostingDeliverySchemaName[0:3],
	ListResponseResultOperationPostingDeliverySchemaFBS:         _ListResponseResultOperationPostingDeliverySchemaName[3:6],
	ListResponseResultOperationPostingDeliverySchemaCROSSBORDER: _ListResponseResultOperationPostingDeliverySchemaName[6:17],
	ListResponseResultOperationPostingDeliverySchemaRFBS:        _ListResponseResultOperationPostingDeliverySchemaName[17:21],
	ListResponseResultOperationPostingDeliverySchemaFBP:         _ListResponseResultOperationPostingDeliverySchemaName[21:24],
	ListResponseResultOperationPostingDeliverySchemaFBOECONOMY:  _ListResponseResultOperationPostingDeliverySchemaName[24:34],
	ListResponseResultOperationPostingDeliverySchemaFBSECONOMY:  _ListResponseResultOperationPostingDeliverySchemaName[34:44],
}

// String implements the Stringer interface.
func (x ListResponseResultOperationPostingDeliverySchema) String() string {
	if str, ok := _ListResponseResultOperationPostingDeliverySchemaMap[x]; ok {
		return str
	}
	return fmt.Sprintf("ListResponseResultOperationPostingDeliverySchema(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ListResponseResultOperationPostingDeliverySchema) IsValid() bool {
	_, ok := _ListResponseResultOperationPostingDeliverySchemaMap[x]
	return ok
}

var _ListResponseResultOperationPostingDeliverySchemaValue = map[string]ListResponseResultOperationPostingDeliverySchema{
	_ListResponseResultOperationPostingDeliverySchemaName[0:3]:   ListResponseResultOperationPostingDeliverySchemaFBO,
	_ListResponseResultOperationPostingDeliverySchemaName[3:6]:   ListResponseResultOperationPostingDeliverySchemaFBS,
	_ListResponseResultOperationPostingDeliverySchemaName[6:17]:  ListResponseResultOperationPostingDeliverySchemaCROSSBORDER,
	_ListResponseResultOperationPostingDeliverySchemaName[17:21]: ListResponseResultOperationPostingDeliverySchemaRFBS,
	_ListResponseResultOperationPostingDeliverySchemaName[21:24]: ListResponseResultOperationPostingDeliverySchemaFBP,
	_ListResponseResultOperationPostingDeliverySchemaName[24:34]: ListResponseResultOperationPostingDeliverySchemaFBOECONOMY,
	_ListResponseResultOperationPostingDeliverySchemaName[34:44]: ListResponseResultOperationPostingDeliverySchemaFBSECONOMY,
}

// ParseListResponseResultOperationPostingDeliverySchema attempts to convert a string to a ListResponseResultOperationPostingDeliverySchema.
func ParseListResponseResultOperationPostingDeliverySchema(name string) (ListResponseResultOperationPostingDeliverySchema, error) {
	if x, ok := _ListResponseResultOperationPostingDeliverySchemaValue[name]; ok {
		return x, nil
	}
	return ListResponseResultOperationPostingDeliverySchema(0), fmt.Errorf("%s is %w", name, ErrInvalidListResponseResultOperationPostingDeliverySchema)
}

// MarshalText implements the text marshaller method.
func (x ListResponseResultOperationPostingDeliverySchema) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *ListResponseResultOperationPostingDeliverySchema) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseListResponseResultOperationPostingDeliverySchema(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

const (
	// ListResponseResultOperationServiceNameMarketplaceNotDeliveredCostItem is a ListResponseResultOperationServiceName of type MarketplaceNotDeliveredCostItem.
	ListResponseResultOperationServiceNameMarketplaceNotDeliveredCostItem ListResponseResultOperationServiceName = iota + 1
	// ListResponseResultOperationServiceNameMarketplaceReturnAfterDeliveryCostItem is a ListResponseResultOperationServiceName of type MarketplaceReturnAfterDeliveryCostItem.
	ListResponseResultOperationServiceNameMarketplaceReturnAfterDeliveryCostItem
	// ListResponseResultOperationServiceNameMarketplaceDeliveryCostItem is a ListResponseResultOperationServiceName of type MarketplaceDeliveryCostItem.
	ListResponseResultOperationServiceNameMarketplaceDeliveryCostItem
	// ListResponseResultOperationServiceNameMarketplaceSaleReviewsItem is a ListResponseResultOperationServiceName of type MarketplaceSaleReviewsItem.
	ListResponseResultOperationServiceNameMarketplaceSaleReviewsItem
	// ListResponseResultOperationServiceNameItemAdvertisementForSupplierLogistic is a ListResponseResultOperationServiceName of type ItemAdvertisementForSupplierLogistic.
	ListResponseResultOperationServiceNameItemAdvertisementForSupplierLogistic
	// ListResponseResultOperationServiceNameOperationMarketplaceServiceStorage is a ListResponseResultOperationServiceName of type OperationMarketplaceServiceStorage.
	ListResponseResultOperationServiceNameOperationMarketplaceServiceStorage
	// ListResponseResultOperationServiceNameMarketplaceMarketingActionCostItem is a ListResponseResultOperationServiceName of type MarketplaceMarketingActionCostItem.
	ListResponseResultOperationServiceNameMarketplaceMarketingActionCostItem
	// ListResponseResultOperationServiceNameMarketplaceServiceItemInstallment is a ListResponseResultOperationServiceName of type MarketplaceServiceItemInstallment.
	ListResponseResultOperationServiceNameMarketplaceServiceItemInstallment
	// ListResponseResultOperationServiceNameMarketplaceServiceItemMarkingItems is a ListResponseResultOperationServiceName of type MarketplaceServiceItemMarkingItems.
	ListResponseResultOperationServiceNameMarketplaceServiceItemMarkingItems
	// ListResponseResultOperationServiceNameMarketplaceServiceItemFlexiblePaymentSchedule is a ListResponseResultOperationServiceName of type MarketplaceServiceItemFlexiblePaymentSchedule.
	ListResponseResultOperationServiceNameMarketplaceServiceItemFlexiblePaymentSchedule
	// ListResponseResultOperationServiceNameMarketplaceServiceItemReturnFromStock is a ListResponseResultOperationServiceName of type MarketplaceServiceItemReturnFromStock.
	ListResponseResultOperationServiceNameMarketplaceServiceItemReturnFromStock
	// ListResponseResultOperationServiceNameItemAdvertisementForSupplierLogisticSeller is a ListResponseResultOperationServiceName of type ItemAdvertisementForSupplierLogisticSeller.
	ListResponseResultOperationServiceNameItemAdvertisementForSupplierLogisticSeller
	// ListResponseResultOperationServiceNameItemAgentServiceStarsMembership is a ListResponseResultOperationServiceName of type ItemAgentServiceStarsMembership.
	ListResponseResultOperationServiceNameItemAgentServiceStarsMembership
	// ListResponseResultOperationServiceNameMarketplaceServiceItemDelivToCustomer is a ListResponseResultOperationServiceName of type MarketplaceServiceItemDelivToCustomer.
	ListResponseResultOperationServiceNameMarketplaceServiceItemDelivToCustomer
	// ListResponseResultOperationServiceNameMarketplaceServiceItemDirectFlowTrans is a ListResponseResultOperationServiceName of type MarketplaceServiceItemDirectFlowTrans.
	ListResponseResultOperationServiceNameMarketplaceServiceItemDirectFlowTrans
	// ListResponseResultOperationServiceNameMarketplaceServiceItemDropoffFF is a ListResponseResultOperationServiceName of type MarketplaceServiceItemDropoffFF.
	ListResponseResultOperationServiceNameMarketplaceServiceItemDropoffFF
	// ListResponseResultOperationServiceNameMarketplaceServiceItemDropoffPVZ is a ListResponseResultOperationServiceName of type MarketplaceServiceItemDropoffPVZ.
	ListResponseResultOperationServiceNameMarketplaceServiceItemDropoffPVZ
	// ListResponseResultOperationServiceNameMarketplaceServiceItemDropoffSC is a ListResponseResultOperationServiceName of type MarketplaceServiceItemDropoffSC.
	ListResponseResultOperationServiceNameMarketplaceServiceItemDropoffSC
	// ListResponseResultOperationServiceNameMarketplaceServiceItemFulfillment is a ListResponseResultOperationServiceName of type MarketplaceServiceItemFulfillment.
	ListResponseResultOperationServiceNameMarketplaceServiceItemFulfillment
	// ListResponseResultOperationServiceNameMarketplaceServiceItemPickup is a ListResponseResultOperationServiceName of type MarketplaceServiceItemPickup.
	ListResponseResultOperationServiceNameMarketplaceServiceItemPickup
	// ListResponseResultOperationServiceNameMarketplaceServiceItemReturnAfterDelivToCustomer is a ListResponseResultOperationServiceName of type MarketplaceServiceItemReturnAfterDelivToCustomer.
	ListResponseResultOperationServiceNameMarketplaceServiceItemReturnAfterDelivToCustomer
	// ListResponseResultOperationServiceNameMarketplaceServiceItemReturnFlowTrans is a ListResponseResultOperationServiceName of type MarketplaceServiceItemReturnFlowTrans.
	ListResponseResultOperationServiceNameMarketplaceServiceItemReturnFlowTrans
	// ListResponseResultOperationServiceNameMarketplaceServiceItemReturnNotDelivToCustomer is a ListResponseResultOperationServiceName of type MarketplaceServiceItemReturnNotDelivToCustomer.
	ListResponseResultOperationServiceNameMarketplaceServiceItemReturnNotDelivToCustomer
	// ListResponseResultOperationServiceNameMarketplaceServiceItemReturnPartGoodsCustomer is a ListResponseResultOperationServiceName of type MarketplaceServiceItemReturnPartGoodsCustomer.
	ListResponseResultOperationServiceNameMarketplaceServiceItemReturnPartGoodsCustomer
	// ListResponseResultOperationServiceNameMarketplaceRedistributionOfAcquiringOperation is a ListResponseResultOperationServiceName of type MarketplaceRedistributionOfAcquiringOperation.
	ListResponseResultOperationServiceNameMarketplaceRedistributionOfAcquiringOperation
	// ListResponseResultOperationServiceNameMarketplaceReturnStorageServiceAtThePickupPointFbsItem is a ListResponseResultOperationServiceName of type MarketplaceReturnStorageServiceAtThePickupPointFbsItem.
	ListResponseResultOperationServiceNameMarketplaceReturnStorageServiceAtThePickupPointFbsItem
	// ListResponseResultOperationServiceNameMarketplaceReturnStorageServiceInTheWarehouseFbsItem is a ListResponseResultOperationServiceName of type MarketplaceReturnStorageServiceInTheWarehouseFbsItem.
	ListResponseResultOperationServiceNameMarketplaceReturnStorageServiceInTheWarehouseFbsItem
	// ListResponseResultOperationServiceNameMarketplaceServiceItemDeliveryKGT is a ListResponseResultOperationServiceName of type MarketplaceServiceItemDeliveryKGT.
	ListResponseResultOperationServiceNameMarketplaceServiceItemDeliveryKGT
	// ListResponseResultOperationServiceNameMarketplaceServiceItemDirectFlowLogistic is a ListResponseResultOperationServiceName of type MarketplaceServiceItemDirectFlowLogistic.
	ListResponseResultOperationServiceNameMarketplaceServiceItemDirectFlowLogistic
	// ListResponseResultOperationServiceNameMarketplaceServiceItemReturnFlowLogistic is a ListResponseResultOperationServiceName of type MarketplaceServiceItemReturnFlowLogistic.
	ListResponseResultOperationServiceNameMarketplaceServiceItemReturnFlowLogistic
	// ListResponseResultOperationServiceNameMarketplaceServicePremiumCashbackIndividualPoints is a ListResponseResultOperationServiceName of type MarketplaceServicePremiumCashbackIndividualPoints.
	ListResponseResultOperationServiceNameMarketplaceServicePremiumCashbackIndividualPoints
	// ListResponseResultOperationServiceNameMarketplaceServicePremiumPromotion is a ListResponseResultOperationServiceName of type MarketplaceServicePremiumPromotion.
	ListResponseResultOperationServiceNameMarketplaceServicePremiumPromotion
	// ListResponseResultOperationServiceNameOperationMarketplaceWithHoldingForUndeliverableGoods is a ListResponseResultOperationServiceName of type OperationMarketplaceWithHoldingForUndeliverableGoods.
	ListResponseResultOperationServiceNameOperationMarketplaceWithHoldingForUndeliverableGoods
	// ListResponseResultOperationServiceNameMarketplaceServiceItemDropoffPPZ is a ListResponseResultOperationServiceName of type MarketplaceServiceItemDropoffPPZ.
	ListResponseResultOperationServiceNameMarketplaceServiceItemDropoffPPZ
	// ListResponseResultOperationServiceNameMarketplaceServiceItemRedistributionReturnsPVZ is a ListResponseResultOperationServiceName of type MarketplaceServiceItemRedistributionReturnsPVZ.
	ListResponseResultOperationServiceNameMarketplaceServiceItemRedistributionReturnsPVZ
	// ListResponseResultOperationServiceNameOperationMarketplaceAgencyFeeAggregator3PLGlobal is a ListResponseResultOperationServiceName of type OperationMarketplaceAgencyFeeAggregator3PLGlobal.
	ListResponseResultOperationServiceNameOperationMarketplaceAgencyFeeAggregator3PLGlobal
	// ListResponseResultOperationServiceNameMarketplaceServiceItemDirectFlowLogisticVDC is a ListResponseResultOperationServiceName of type MarketplaceServiceItemDirectFlowLogisticVDC.
	ListResponseResultOperationServiceNameMarketplaceServiceItemDirectFlowLogisticVDC
)

var ErrInvalidListResponseResultOperationServiceName = fmt.Errorf("not a valid ListResponseResultOperationServiceName, try [%s]", strings.Join(_ListResponseResultOperationServiceNameNames, ", "))

const _ListResponseResultOperationServiceNameName = "MarketplaceNotDeliveredCostItemMarketplaceReturnAfterDeliveryCostItemMarketplaceDeliveryCostItemMarketplaceSaleReviewsItemItemAdvertisementForSupplierLogisticOperationMarketplaceServiceStorageMarketplaceMarketingActionCostItemMarketplaceServiceItemInstallmentMarketplaceServiceItemMarkingItemsMarketplaceServiceItemFlexiblePaymentScheduleMarketplaceServiceItemReturnFromStockItemAdvertisementForSupplierLogisticSellerItemAgentServiceStarsMembershipMarketplaceServiceItemDelivToCustomerMarketplaceServiceItemDirectFlowTransMarketplaceServiceItemDropoffFFMarketplaceServiceItemDropoffPVZMarketplaceServiceItemDropoffSCMarketplaceServiceItemFulfillmentMarketplaceServiceItemPickupMarketplaceServiceItemReturnAfterDelivToCustomerMarketplaceServiceItemReturnFlowTransMarketplaceServiceItemReturnNotDelivToCustomerMarketplaceServiceItemReturnPartGoodsCustomerMarketplaceRedistributionOfAcquiringOperationMarketplaceReturnStorageServiceAtThePickupPointFbsItemMarketplaceReturnStorageServiceInTheWarehouseFbsItemMarketplaceServiceItemDeliveryKGTMarketplaceServiceItemDirectFlowLogisticMarketplaceServiceItemReturnFlowLogisticMarketplaceServicePremiumCashbackIndividualPointsMarketplaceServicePremiumPromotionOperationMarketplaceWithHoldingForUndeliverableGoodsMarketplaceServiceItemDropoffPPZMarketplaceServiceItemRedistributionReturnsPVZOperationMarketplaceAgencyFeeAggregator3PLGlobalMarketplaceServiceItemDirectFlowLogisticVDC"

var _ListResponseResultOperationServiceNameNames = []string{
	_ListResponseResultOperationServiceNameName[0:31],
	_ListResponseResultOperationServiceNameName[31:69],
	_ListResponseResultOperationServiceNameName[69:96],
	_ListResponseResultOperationServiceNameName[96:122],
	_ListResponseResultOperationServiceNameName[122:158],
	_ListResponseResultOperationServiceNameName[158:192],
	_ListResponseResultOperationServiceNameName[192:226],
	_ListResponseResultOperationServiceNameName[226:259],
	_ListResponseResultOperationServiceNameName[259:293],
	_ListResponseResultOperationServiceNameName[293:338],
	_ListResponseResultOperationServiceNameName[338:375],
	_ListResponseResultOperationServiceNameName[375:417],
	_ListResponseResultOperationServiceNameName[417:448],
	_ListResponseResultOperationServiceNameName[448:485],
	_ListResponseResultOperationServiceNameName[485:522],
	_ListResponseResultOperationServiceNameName[522:553],
	_ListResponseResultOperationServiceNameName[553:585],
	_ListResponseResultOperationServiceNameName[585:616],
	_ListResponseResultOperationServiceNameName[616:649],
	_ListResponseResultOperationServiceNameName[649:677],
	_ListResponseResultOperationServiceNameName[677:725],
	_ListResponseResultOperationServiceNameName[725:762],
	_ListResponseResultOperationServiceNameName[762:808],
	_ListResponseResultOperationServiceNameName[808:853],
	_ListResponseResultOperationServiceNameName[853:898],
	_ListResponseResultOperationServiceNameName[898:952],
	_ListResponseResultOperationServiceNameName[952:1004],
	_ListResponseResultOperationServiceNameName[1004:1037],
	_ListResponseResultOperationServiceNameName[1037:1077],
	_ListResponseResultOperationServiceNameName[1077:1117],
	_ListResponseResultOperationServiceNameName[1117:1166],
	_ListResponseResultOperationServiceNameName[1166:1200],
	_ListResponseResultOperationServiceNameName[1200:1252],
	_ListResponseResultOperationServiceNameName[1252:1284],
	_ListResponseResultOperationServiceNameName[1284:1330],
	_ListResponseResultOperationServiceNameName[1330:1378],
	_ListResponseResultOperationServiceNameName[1378:1421],
}

// ListResponseResultOperationServiceNameNames returns a list of possible string values of ListResponseResultOperationServiceName.
func ListResponseResultOperationServiceNameNames() []string {
	tmp := make([]string, len(_ListResponseResultOperationServiceNameNames))
	copy(tmp, _ListResponseResultOperationServiceNameNames)
	return tmp
}

var _ListResponseResultOperationServiceNameMap = map[ListResponseResultOperationServiceName]string{
	ListResponseResultOperationServiceNameMarketplaceNotDeliveredCostItem:                        _ListResponseResultOperationServiceNameName[0:31],
	ListResponseResultOperationServiceNameMarketplaceReturnAfterDeliveryCostItem:                 _ListResponseResultOperationServiceNameName[31:69],
	ListResponseResultOperationServiceNameMarketplaceDeliveryCostItem:                            _ListResponseResultOperationServiceNameName[69:96],
	ListResponseResultOperationServiceNameMarketplaceSaleReviewsItem:                             _ListResponseResultOperationServiceNameName[96:122],
	ListResponseResultOperationServiceNameItemAdvertisementForSupplierLogistic:                   _ListResponseResultOperationServiceNameName[122:158],
	ListResponseResultOperationServiceNameOperationMarketplaceServiceStorage:                     _ListResponseResultOperationServiceNameName[158:192],
	ListResponseResultOperationServiceNameMarketplaceMarketingActionCostItem:                     _ListResponseResultOperationServiceNameName[192:226],
	ListResponseResultOperationServiceNameMarketplaceServiceItemInstallment:                      _ListResponseResultOperationServiceNameName[226:259],
	ListResponseResultOperationServiceNameMarketplaceServiceItemMarkingItems:                     _ListResponseResultOperationServiceNameName[259:293],
	ListResponseResultOperationServiceNameMarketplaceServiceItemFlexiblePaymentSchedule:          _ListResponseResultOperationServiceNameName[293:338],
	ListResponseResultOperationServiceNameMarketplaceServiceItemReturnFromStock:                  _ListResponseResultOperationServiceNameName[338:375],
	ListResponseResultOperationServiceNameItemAdvertisementForSupplierLogisticSeller:             _ListResponseResultOperationServiceNameName[375:417],
	ListResponseResultOperationServiceNameItemAgentServiceStarsMembership:                        _ListResponseResultOperationServiceNameName[417:448],
	ListResponseResultOperationServiceNameMarketplaceServiceItemDelivToCustomer:                  _ListResponseResultOperationServiceNameName[448:485],
	ListResponseResultOperationServiceNameMarketplaceServiceItemDirectFlowTrans:                  _ListResponseResultOperationServiceNameName[485:522],
	ListResponseResultOperationServiceNameMarketplaceServiceItemDropoffFF:                        _ListResponseResultOperationServiceNameName[522:553],
	ListResponseResultOperationServiceNameMarketplaceServiceItemDropoffPVZ:                       _ListResponseResultOperationServiceNameName[553:585],
	ListResponseResultOperationServiceNameMarketplaceServiceItemDropoffSC:                        _ListResponseResultOperationServiceNameName[585:616],
	ListResponseResultOperationServiceNameMarketplaceServiceItemFulfillment:                      _ListResponseResultOperationServiceNameName[616:649],
	ListResponseResultOperationServiceNameMarketplaceServiceItemPickup:                           _ListResponseResultOperationServiceNameName[649:677],
	ListResponseResultOperationServiceNameMarketplaceServiceItemReturnAfterDelivToCustomer:       _ListResponseResultOperationServiceNameName[677:725],
	ListResponseResultOperationServiceNameMarketplaceServiceItemReturnFlowTrans:                  _ListResponseResultOperationServiceNameName[725:762],
	ListResponseResultOperationServiceNameMarketplaceServiceItemReturnNotDelivToCustomer:         _ListResponseResultOperationServiceNameName[762:808],
	ListResponseResultOperationServiceNameMarketplaceServiceItemReturnPartGoodsCustomer:          _ListResponseResultOperationServiceNameName[808:853],
	ListResponseResultOperationServiceNameMarketplaceRedistributionOfAcquiringOperation:          _ListResponseResultOperationServiceNameName[853:898],
	ListResponseResultOperationServiceNameMarketplaceReturnStorageServiceAtThePickupPointFbsItem: _ListResponseResultOperationServiceNameName[898:952],
	ListResponseResultOperationServiceNameMarketplaceReturnStorageServiceInTheWarehouseFbsItem:   _ListResponseResultOperationServiceNameName[952:1004],
	ListResponseResultOperationServiceNameMarketplaceServiceItemDeliveryKGT:                      _ListResponseResultOperationServiceNameName[1004:1037],
	ListResponseResultOperationServiceNameMarketplaceServiceItemDirectFlowLogistic:               _ListResponseResultOperationServiceNameName[1037:1077],
	ListResponseResultOperationServiceNameMarketplaceServiceItemReturnFlowLogistic:               _ListResponseResultOperationServiceNameName[1077:1117],
	ListResponseResultOperationServiceNameMarketplaceServicePremiumCashbackIndividualPoints:      _ListResponseResultOperationServiceNameName[1117:1166],
	ListResponseResultOperationServiceNameMarketplaceServicePremiumPromotion:                     _ListResponseResultOperationServiceNameName[1166:1200],
	ListResponseResultOperationServiceNameOperationMarketplaceWithHoldingForUndeliverableGoods:   _ListResponseResultOperationServiceNameName[1200:1252],
	ListResponseResultOperationServiceNameMarketplaceServiceItemDropoffPPZ:                       _ListResponseResultOperationServiceNameName[1252:1284],
	ListResponseResultOperationServiceNameMarketplaceServiceItemRedistributionReturnsPVZ:         _ListResponseResultOperationServiceNameName[1284:1330],
	ListResponseResultOperationServiceNameOperationMarketplaceAgencyFeeAggregator3PLGlobal:       _ListResponseResultOperationServiceNameName[1330:1378],
	ListResponseResultOperationServiceNameMarketplaceServiceItemDirectFlowLogisticVDC:            _ListResponseResultOperationServiceNameName[1378:1421],
}

// String implements the Stringer interface.
func (x ListResponseResultOperationServiceName) String() string {
	if str, ok := _ListResponseResultOperationServiceNameMap[x]; ok {
		return str
	}
	return fmt.Sprintf("ListResponseResultOperationServiceName(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ListResponseResultOperationServiceName) IsValid() bool {
	_, ok := _ListResponseResultOperationServiceNameMap[x]
	return ok
}

var _ListResponseResultOperationServiceNameValue = map[string]ListResponseResultOperationServiceName{
	_ListResponseResultOperationServiceNameName[0:31]:      ListResponseResultOperationServiceNameMarketplaceNotDeliveredCostItem,
	_ListResponseResultOperationServiceNameName[31:69]:     ListResponseResultOperationServiceNameMarketplaceReturnAfterDeliveryCostItem,
	_ListResponseResultOperationServiceNameName[69:96]:     ListResponseResultOperationServiceNameMarketplaceDeliveryCostItem,
	_ListResponseResultOperationServiceNameName[96:122]:    ListResponseResultOperationServiceNameMarketplaceSaleReviewsItem,
	_ListResponseResultOperationServiceNameName[122:158]:   ListResponseResultOperationServiceNameItemAdvertisementForSupplierLogistic,
	_ListResponseResultOperationServiceNameName[158:192]:   ListResponseResultOperationServiceNameOperationMarketplaceServiceStorage,
	_ListResponseResultOperationServiceNameName[192:226]:   ListResponseResultOperationServiceNameMarketplaceMarketingActionCostItem,
	_ListResponseResultOperationServiceNameName[226:259]:   ListResponseResultOperationServiceNameMarketplaceServiceItemInstallment,
	_ListResponseResultOperationServiceNameName[259:293]:   ListResponseResultOperationServiceNameMarketplaceServiceItemMarkingItems,
	_ListResponseResultOperationServiceNameName[293:338]:   ListResponseResultOperationServiceNameMarketplaceServiceItemFlexiblePaymentSchedule,
	_ListResponseResultOperationServiceNameName[338:375]:   ListResponseResultOperationServiceNameMarketplaceServiceItemReturnFromStock,
	_ListResponseResultOperationServiceNameName[375:417]:   ListResponseResultOperationServiceNameItemAdvertisementForSupplierLogisticSeller,
	_ListResponseResultOperationServiceNameName[417:448]:   ListResponseResultOperationServiceNameItemAgentServiceStarsMembership,
	_ListResponseResultOperationServiceNameName[448:485]:   ListResponseResultOperationServiceNameMarketplaceServiceItemDelivToCustomer,
	_ListResponseResultOperationServiceNameName[485:522]:   ListResponseResultOperationServiceNameMarketplaceServiceItemDirectFlowTrans,
	_ListResponseResultOperationServiceNameName[522:553]:   ListResponseResultOperationServiceNameMarketplaceServiceItemDropoffFF,
	_ListResponseResultOperationServiceNameName[553:585]:   ListResponseResultOperationServiceNameMarketplaceServiceItemDropoffPVZ,
	_ListResponseResultOperationServiceNameName[585:616]:   ListResponseResultOperationServiceNameMarketplaceServiceItemDropoffSC,
	_ListResponseResultOperationServiceNameName[616:649]:   ListResponseResultOperationServiceNameMarketplaceServiceItemFulfillment,
	_ListResponseResultOperationServiceNameName[649:677]:   ListResponseResultOperationServiceNameMarketplaceServiceItemPickup,
	_ListResponseResultOperationServiceNameName[677:725]:   ListResponseResultOperationServiceNameMarketplaceServiceItemReturnAfterDelivToCustomer,
	_ListResponseResultOperationServiceNameName[725:762]:   ListResponseResultOperationServiceNameMarketplaceServiceItemReturnFlowTrans,
	_ListResponseResultOperationServiceNameName[762:808]:   ListResponseResultOperationServiceNameMarketplaceServiceItemReturnNotDelivToCustomer,
	_ListResponseResultOperationServiceNameName[808:853]:   ListResponseResultOperationServiceNameMarketplaceServiceItemReturnPartGoodsCustomer,
	_ListResponseResultOperationServiceNameName[853:898]:   ListResponseResultOperationServiceNameMarketplaceRedistributionOfAcquiringOperation,
	_ListResponseResultOperationServiceNameName[898:952]:   ListResponseResultOperationServiceNameMarketplaceReturnStorageServiceAtThePickupPointFbsItem,
	_ListResponseResultOperationServiceNameName[952:1004]:  ListResponseResultOperationServiceNameMarketplaceReturnStorageServiceInTheWarehouseFbsItem,
	_ListResponseResultOperationServiceNameName[1004:1037]: ListResponseResultOperationServiceNameMarketplaceServiceItemDeliveryKGT,
	_ListResponseResultOperationServiceNameName[1037:1077]: ListResponseResultOperationServiceNameMarketplaceServiceItemDirectFlowLogistic,
	_ListResponseResultOperationServiceNameName[1077:1117]: ListResponseResultOperationServiceNameMarketplaceServiceItemReturnFlowLogistic,
	_ListResponseResultOperationServiceNameName[1117:1166]: ListResponseResultOperationServiceNameMarketplaceServicePremiumCashbackIndividualPoints,
	_ListResponseResultOperationServiceNameName[1166:1200]: ListResponseResultOperationServiceNameMarketplaceServicePremiumPromotion,
	_ListResponseResultOperationServiceNameName[1200:1252]: ListResponseResultOperationServiceNameOperationMarketplaceWithHoldingForUndeliverableGoods,
	_ListResponseResultOperationServiceNameName[1252:1284]: ListResponseResultOperationServiceNameMarketplaceServiceItemDropoffPPZ,
	_ListResponseResultOperationServiceNameName[1284:1330]: ListResponseResultOperationServiceNameMarketplaceServiceItemRedistributionReturnsPVZ,
	_ListResponseResultOperationServiceNameName[1330:1378]: ListResponseResultOperationServiceNameOperationMarketplaceAgencyFeeAggregator3PLGlobal,
	_ListResponseResultOperationServiceNameName[1378:1421]: ListResponseResultOperationServiceNameMarketplaceServiceItemDirectFlowLogisticVDC,
}

// ParseListResponseResultOperationServiceName attempts to convert a string to a ListResponseResultOperationServiceName.
func ParseListResponseResultOperationServiceName(name string) (ListResponseResultOperationServiceName, error) {
	if x, ok := _ListResponseResultOperationServiceNameValue[name]; ok {
		return x, nil
	}
	return ListResponseResultOperationServiceName(0), fmt.Errorf("%s is %w", name, ErrInvalidListResponseResultOperationServiceName)
}

// MarshalText implements the text marshaller method.
func (x ListResponseResultOperationServiceName) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *ListResponseResultOperationServiceName) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseListResponseResultOperationServiceName(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

const (
	// ListResponseResultOperationTypeAll is a ListResponseResultOperationType of type All.
	ListResponseResultOperationTypeAll ListResponseResultOperationType = iota + 1
	// ListResponseResultOperationTypeOrders is a ListResponseResultOperationType of type Orders.
	ListResponseResultOperationTypeOrders
	// ListResponseResultOperationTypeReturns is a ListResponseResultOperationType of type Returns.
	ListResponseResultOperationTypeReturns
	// ListResponseResultOperationTypeServices is a ListResponseResultOperationType of type Services.
	ListResponseResultOperationTypeServices
	// ListResponseResultOperationTypeCompensation is a ListResponseResultOperationType of type Compensation.
	ListResponseResultOperationTypeCompensation
	// ListResponseResultOperationTypeTransferDelivery is a ListResponseResultOperationType of type TransferDelivery.
	ListResponseResultOperationTypeTransferDelivery
	// ListResponseResultOperationTypeOther is a ListResponseResultOperationType of type Other.
	ListResponseResultOperationTypeOther
)

var ErrInvalidListResponseResultOperationType = fmt.Errorf("not a valid ListResponseResultOperationType, try [%s]", strings.Join(_ListResponseResultOperationTypeNames, ", "))

const _ListResponseResultOperationTypeName = "allordersreturnsservicescompensationtransferDeliveryother"

var _ListResponseResultOperationTypeNames = []string{
	_ListResponseResultOperationTypeName[0:3],
	_ListResponseResultOperationTypeName[3:9],
	_ListResponseResultOperationTypeName[9:16],
	_ListResponseResultOperationTypeName[16:24],
	_ListResponseResultOperationTypeName[24:36],
	_ListResponseResultOperationTypeName[36:52],
	_ListResponseResultOperationTypeName[52:57],
}

// ListResponseResultOperationTypeNames returns a list of possible string values of ListResponseResultOperationType.
func ListResponseResultOperationTypeNames() []string {
	tmp := make([]string, len(_ListResponseResultOperationTypeNames))
	copy(tmp, _ListResponseResultOperationTypeNames)
	return tmp
}

var _ListResponseResultOperationTypeMap = map[ListResponseResultOperationType]string{
	ListResponseResultOperationTypeAll:              _ListResponseResultOperationTypeName[0:3],
	ListResponseResultOperationTypeOrders:           _ListResponseResultOperationTypeName[3:9],
	ListResponseResultOperationTypeReturns:          _ListResponseResultOperationTypeName[9:16],
	ListResponseResultOperationTypeServices:         _ListResponseResultOperationTypeName[16:24],
	ListResponseResultOperationTypeCompensation:     _ListResponseResultOperationTypeName[24:36],
	ListResponseResultOperationTypeTransferDelivery: _ListResponseResultOperationTypeName[36:52],
	ListResponseResultOperationTypeOther:            _ListResponseResultOperationTypeName[52:57],
}

// String implements the Stringer interface.
func (x ListResponseResultOperationType) String() string {
	if str, ok := _ListResponseResultOperationTypeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("ListResponseResultOperationType(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ListResponseResultOperationType) IsValid() bool {
	_, ok := _ListResponseResultOperationTypeMap[x]
	return ok
}

var _ListResponseResultOperationTypeValue = map[string]ListResponseResultOperationType{
	_ListResponseResultOperationTypeName[0:3]:   ListResponseResultOperationTypeAll,
	_ListResponseResultOperationTypeName[3:9]:   ListResponseResultOperationTypeOrders,
	_ListResponseResultOperationTypeName[9:16]:  ListResponseResultOperationTypeReturns,
	_ListResponseResultOperationTypeName[16:24]: ListResponseResultOperationTypeServices,
	_ListResponseResultOperationTypeName[24:36]: ListResponseResultOperationTypeCompensation,
	_ListResponseResultOperationTypeName[36:52]: ListResponseResultOperationTypeTransferDelivery,
	_ListResponseResultOperationTypeName[52:57]: ListResponseResultOperationTypeOther,
}

// ParseListResponseResultOperationType attempts to convert a string to a ListResponseResultOperationType.
func ParseListResponseResultOperationType(name string) (ListResponseResultOperationType, error) {
	if x, ok := _ListResponseResultOperationTypeValue[name]; ok {
		return x, nil
	}
	return ListResponseResultOperationType(0), fmt.Errorf("%s is %w", name, ErrInvalidListResponseResultOperationType)
}

// MarshalText implements the text marshaller method.
func (x ListResponseResultOperationType) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *ListResponseResultOperationType) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseListResponseResultOperationType(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}
