package transaction

//go:generate go run github.com/abice/go-enum -f=$GOFILE --marshal --names

// ListResponseResultOperationPostingDeliverySchema
// ENUM(FBO=1, FBS, CROSSBORDER, RFBS, FBP, FBOECONOMY, FBSECONOMY)
type ListResponseResultOperationPostingDeliverySchema int32

// ListResponseResultOperationType
// ENUM(all=1, orders, returns, services, compensation, transferDelivery, other)
type ListResponseResultOperationType int32

// ListResponseResultOperationServiceName
// ENUM(MarketplaceNotDeliveredCostItem=1, MarketplaceReturnAfterDeliveryCostItem, MarketplaceDeliveryCostItem, MarketplaceSaleReviewsItem, ItemAdvertisementForSupplierLogistic, OperationMarketplaceServiceStorage, MarketplaceMarketingActionCostItem, MarketplaceServiceItemInstallment, MarketplaceServiceItemMarkingItems, MarketplaceServiceItemFlexiblePaymentSchedule, MarketplaceServiceItemReturnFromStock, ItemAdvertisementForSupplierLogisticSeller, ItemAgentServiceStarsMembership, MarketplaceServiceItemDelivToCustomer, MarketplaceServiceItemDirectFlowTrans, MarketplaceServiceItemDropoffFF, MarketplaceServiceItemDropoffPVZ, MarketplaceServiceItemDropoffSC, MarketplaceServiceItemFulfillment, MarketplaceServiceItemPickup, MarketplaceServiceItemReturnAfterDelivToCustomer, MarketplaceServiceItemReturnFlowTrans, MarketplaceServiceItemReturnNotDelivToCustomer, MarketplaceServiceItemReturnPartGoodsCustomer, MarketplaceRedistributionOfAcquiringOperation, MarketplaceReturnStorageServiceAtThePickupPointFbsItem, MarketplaceReturnStorageServiceInTheWarehouseFbsItem, MarketplaceServiceItemDeliveryKGT, MarketplaceServiceItemDirectFlowLogistic, MarketplaceServiceItemReturnFlowLogistic, MarketplaceServicePremiumCashbackIndividualPoints, MarketplaceServicePremiumPromotion, OperationMarketplaceWithHoldingForUndeliverableGoods, MarketplaceServiceItemDropoffPPZ, MarketplaceServiceItemRedistributionReturnsPVZ, OperationMarketplaceAgencyFeeAggregator3PLGlobal, MarketplaceServiceItemDirectFlowLogisticVDC)
type ListResponseResultOperationServiceName int32
