name: tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  unit:
    runs-on: ubuntu-latest
    steps:
    
    - name: Check out code
      uses: actions/checkout@v3

    - name: Unit Tests
      run: go test -v ./...